test : tree_etu.o fonc_etu.o main.o
	gcc -g -Wall tree_etu.o fonc_etu.o main.o list.o -o test

main : main.c
	gcc -Wall -c main.c

fonc : fonc_etu.c
	gcc -Wall -c fonc_etu.c

tree : tree_etu.c
	gcc -Wall -c tree_etu.c